steps:
  - id: 'Populate Maven cache from bucket'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/miniwe/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - id: 'Set MiniWE client release versions'
    name: 'maven:3.9.1-eclipse-temurin-11'
    entrypoint: 'mvn'
    args: [ 'versions:set', '-DnewVersion=${TAG_NAME}', '--batch-mode' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

  - id: 'Compile, package, and release'
    name: 'maven:3.9.1-eclipse-temurin-11'
    entrypoint: 'mvn'
    args: ['deploy', '--batch-mode']
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

  - id: 'Refresh bucket from local Maven cache after build'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/miniwe/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

logsBucket: 'hmf-build-logs'
options:
  machineType: 'E2_HIGHCPU_8'

